// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventEmitterClient is the client API for EventEmitter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventEmitterClient interface {
	// Sends a greeting
	SendEvent(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type eventEmitterClient struct {
	cc grpc.ClientConnInterface
}

func NewEventEmitterClient(cc grpc.ClientConnInterface) EventEmitterClient {
	return &eventEmitterClient{cc}
}

func (c *eventEmitterClient) SendEvent(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/proto.EventEmitter/SendEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventEmitterServer is the server API for EventEmitter service.
// All implementations must embed UnimplementedEventEmitterServer
// for forward compatibility
type EventEmitterServer interface {
	// Sends a greeting
	SendEvent(context.Context, *MessageRequest) (*MessageResponse, error)
	mustEmbedUnimplementedEventEmitterServer()
}

// UnimplementedEventEmitterServer must be embedded to have forward compatible implementations.
type UnimplementedEventEmitterServer struct {
}

func (UnimplementedEventEmitterServer) SendEvent(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedEventEmitterServer) mustEmbedUnimplementedEventEmitterServer() {}

// UnsafeEventEmitterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventEmitterServer will
// result in compilation errors.
type UnsafeEventEmitterServer interface {
	mustEmbedUnimplementedEventEmitterServer()
}

func RegisterEventEmitterServer(s grpc.ServiceRegistrar, srv EventEmitterServer) {
	s.RegisterService(&EventEmitter_ServiceDesc, srv)
}

func _EventEmitter_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventEmitterServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventEmitter/SendEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventEmitterServer).SendEvent(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventEmitter_ServiceDesc is the grpc.ServiceDesc for EventEmitter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventEmitter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventEmitter",
	HandlerType: (*EventEmitterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _EventEmitter_SendEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
